name: Release

on:
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Read extension version
        id: package
        run: echo "version=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"

      - name: Package extension
        run: npm run package

      - name: Upload VSIX artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/lispbm-language-support-${{ steps.package.outputs.version }}.vsix
